export const SLIDE_INTERVAL_MS = 2000;

// Start with the existing hero, then visit every other supported breed once.
export const breedGallery = [
  ["Nari", "jpg", "नारी", "નારી"],
  ["Amritmahal", "webp", "अमृतमहल", "અમૃતમહાલ"],
  ["Ayrshire", "jpg", "आयरशायर", "આયરશાયર"],
  ["Bachaur", "webp", "बछौर", "બછૌર"],
  ["Badri", "jpg", "बद्री", "બદ્રી"],
  ["Bargur", "jpg", "बरगुर", "બરગુર"],
  ["Belahi", "webp", "बेलाही", "બેલાહી"],
  ["Dagri", "jpg", "डागरी", "ડાગરી"],
  ["Dangi", "webp", "डांगी", "ડાંગી"],
  ["Deoni", "webp", "देवनी", "દેવની"],
  ["Gangatiri", "webp", "गंगातीरी", "ગંગાતીરી"],
  ["Gaolao", "webp", "गावलाओ", "ગાવલાઓ"],
  ["Ghumusari", "webp", "घुमुसारी", "ઘુમુસારી"],
  ["Gir", "webp", "गिर", "ગીર"],
  ["Hallikar", "webp", "हल्लीकर", "હલ્લીકર"],
  ["Hariana", "webp", "हरियाना", "હરિયાણા"],
  ["Himachali Pahari", "jpg", "हिमाचली पहाड़ी", "હિમાચલી પહાડી"],
  ["Kangayam", "webp", "कंगायम", "કાંગાયમ"],
  ["Kankrej", "webp", "कांकरेज", "કાંકરેજ"],
  ["Kenkatha", "webp", "केनकथा", "કેનકથા"],
  ["Khariar", "webp", "खरियार", "ખરિયાર"],
  ["Kherigarh", "webp", "खेरीगढ़", "ખેરીગઢ"],
  ["Khillar", "webp", "खिल्लार", "ખિલ્લાર"],
  ["Kokan Kapila", "webp", "कोंकण कपिला", "કોંકણ કપિલા"],
  ["Kosali", "webp", "कोसली", "કોસલી"],
  ["Krishna Valley", "webp", "कृष्णा वैली", "કૃષ્ણા વેલી"],
  ["Ladakhi", "webp", "लद्दाखी", "લદ્દાખી"],
  ["Lakhimi", "webp", "लखीमी", "લખીમી"],
  ["Malnad Gidda", "webp", "मलनाड गिड्डा", "મલનાડ ગિડ્ડા"],
  ["Malvi", "webp", "मालवी", "માલવી"],
  ["Mewati", "webp", "मेवाती", "મેવાતી"],
  ["Motu", "webp", "मोटू", "મોટુ"],
  ["Nagori", "webp", "नागौरी", "નાગૌરી"],
  ["Nimari", "webp", "निमाड़ी", "નિમાડી"],
  ["Ongole", "webp", "ओंगोल", "ઓંગોલ"],
  ["Poda Thurpu", "jpg", "पोडा थुरपू", "પોડા થુરપુ"],
  ["Ponwar", "webp", "पोनवार", "પોનવાર"],
  ["Pulikulam", "webp", "पुलिकुलम", "પુલિકુલમ"],
  ["Punganur", "webp", "पुंगनूर", "પુંગનૂર"],
  ["Purnea", "jpg", "पूर्णिया", "પૂર્ણિયા"],
  ["Rathi", "webp", "राठी", "રાઠી"],
  ["Red Kandhari", "webp", "लाल कंधारी", "લાલ કંધારી"],
  ["Red Sindhi", "webp", "लाल सिंधी", "લાલ સિંધી"],
  ["Sahiwal", "webp", "साहीवाल", "સાહીવાલ"],
  ["Shweta Kapila", "jpg", "श्वेत कपिला", "શ્વેત કપિલા"],
  ["Siri", "webp", "सिरी", "સિરી"],
  ["Tharparkar", "webp", "थारपारकर", "થારપારકર"],
  ["Thutho", "jpg", "थूथो", "થૂથો"],
  ["Umblachery", "webp", "उम्बलाचेरी", "ઉમ્બલાચેરી"],
  ["Vechur", "webp", "वेचूर", "વેચૂર"],
].map(([id, extension, hi, gu]) => ({
  id,
  image: `/breeds/${id}.${extension}`,
  names: { en: id, hi, gu },
}));
