export const featuredBreeds = [
  { id: "Gir", image: "/breeds/Gir.webp", portrait: true },
  { id: "Kankrej", image: "/breeds/Kankrej.webp", portrait: true },
  { id: "Thutho", image: "/breeds/Thutho.jpg", portrait: false },
];

export const homeParts = ["home-intro", "how-it-works", "breed-collection", "photo-guide"];

export const homeContent = {
  en: {
    language: "Language",
    navigation: "Main navigation",
    skip: "Skip to content",
    carouselRole: "carousel",
    carouselLabel: "Cattle breed photographs",
    previousPhoto: "Previous breed photo",
    nextPhoto: "Next breed photo",
    pauseSlideshow: "Pause slideshow",
    playSlideshow: "Play slideshow",
    reducedSlideshow: "Reduced motion: use the arrows to explore",
    slideshowTiming: "A new breed every 2 seconds",
    photoAlt: "{breed} cattle",
    photoError: "This photo could not load. Use the arrows to choose another breed.",
    identify: "Identify breed",
    explore: "Explore breeds",
    eyebrow: "Rooted in heritage. Guided by AI.",
    title: "Know your cattle.",
    titleAccent: "Discover their story.",
    intro: "A photograph can begin a deeper understanding. Explore cattle breeds, discover their characteristics, and connect with India's rich farming heritage.",
    uploadHint: "Your photo. An AI suggestion. A place to start.",
    fieldNote: "From the breed collection",
    meetBreed: "Meet the breed",
    photoLabel: "Breed photograph, not a prediction",
    supported: "Supported cattle categories",
    languages: "Languages to explore in",
    report: "A report to take with you",
    reportFormat: "PDF",
    processEyebrow: "From photo to knowledge",
    processTitle: "A simple start to a richer understanding.",
    steps: [
      { title: "Share a clear photo", body: "Choose a well-lit image of one animal, with its body, head and horns visible." },
      { title: "Get an AI suggestion", body: "The model suggests a supported breed and a confidence score. Treat it as guidance, not a verified identity." },
      { title: "Learn. Save. Explore.", body: "Read breed characteristics, download a PDF report, or discover more in the breed collection." },
    ],
    collectionEyebrow: "Many breeds. Many stories.",
    collectionTitle: "Meet a few of India's remarkable cattle.",
    collectionIntro: "Different landscapes have shaped different cattle traditions. Discover the diversity behind familiar faces.",
    allBreeds: "View all 50 breeds",
    breedNames: { Gir: "Gir", Kankrej: "Kankrej", Thutho: "Thutho" },
    breedRegions: { Gir: "Gujarat", Kankrej: "Gujarat & Rajasthan", Thutho: "Nagaland" },
    breedNotes: {
      Gir: "A curved forehead and long, pendulous ears distinguish this dairy breed.",
      Kankrej: "A dual-purpose breed, recognised for its striking lyre-shaped horns.",
      Thutho: "Cattle from Nagaland, at home in the region's hilly landscapes.",
    },
    viewProfile: "Explore profile",
    diversity: "Why diversity matters",
    diversityBody: "Learning about local breeds is a step toward valuing livestock diversity, rural livelihoods and the environments they depend on.",
    diversityLink: "Learn more from FAO",
    guideEyebrow: "A better photo. A better starting point.",
    guideTitle: "Let the important details show.",
    tips: [
      { title: "One animal, side-on", body: "Keep the full body in frame, including the head and horns." },
      { title: "Natural, even light", body: "Avoid deep shadows, blur, filters and distant subjects." },
      { title: "Keep personal details out", body: "Choose a photo without people, documents or identifying information." },
    ],
    faqEyebrow: "Before you begin",
    faqTitle: "A few things worth knowing.",
    faqs: [
      { question: "What does the confidence score mean?", answer: "It reflects the model's confidence in its suggestion for that photo, not a guarantee of breed identity. Similar breeds, mixed ancestry or unclear images can lead to mistakes. A photo cannot verify genetics or diagnose health." },
      { question: "Are milk yield and other figures measured from my photo?", answer: "No. Milk yield, fat percentage, climate tolerance and market value are general breed-reference information, not measurements of the individual animal. Actual values vary with care, age, location and other factors." },
      { question: "Is my prediction history private?", answer: "No. This version has shared, public prediction history, not personal accounts. Photos are sent to the server for analysis; history includes prediction details and a timestamp. Do not upload sensitive or personally identifying content." },
      { question: "Why might the first result take longer?", answer: "The free API can sleep when unused and may take time to wake up. Keep the page open while it analyses. If an error appears, wait a little and try again. You can explore the breed collection without an upload." },
    ],
    closingEyebrow: "Curiosity is the first step",
    closingTitle: "Every breed has a story.\nStart discovering.",
    footer: "Discover. Understand. Preserve.",
    footerNote: "AI-assisted learning, not breed verification.",
  },
  hi: {
    language: "भाषा",
    navigation: "मुख्य नेविगेशन",
    skip: "मुख्य सामग्री पर जाएँ",
    carouselRole: "चित्र श्रृंखला",
    carouselLabel: "मवेशियों की नस्लों की तस्वीरें",
    previousPhoto: "पिछली नस्ल की तस्वीर",
    nextPhoto: "अगली नस्ल की तस्वीर",
    pauseSlideshow: "चित्र श्रृंखला रोकें",
    playSlideshow: "चित्र श्रृंखला चलाएँ",
    reducedSlideshow: "कम गति: तस्वीरें देखने के लिए तीरों का उपयोग करें",
    slideshowTiming: "हर 2 सेकंड में एक नई नस्ल",
    photoAlt: "{breed} नस्ल के मवेशी",
    photoError: "यह तस्वीर लोड नहीं हुई। दूसरी नस्ल चुनने के लिए तीरों का उपयोग करें।",
    identify: "नस्ल पहचानें",
    explore: "नस्लें देखें",
    eyebrow: "विरासत से जुड़ाव। एआई का मार्गदर्शन।",
    title: "अपने मवेशियों को जानें।",
    titleAccent: "उनकी कहानी खोजें।",
    intro: "एक तस्वीर से गहरी समझ की शुरुआत हो सकती है। मवेशियों की नस्लें और उनकी विशेषताएँ जानें, और भारत की समृद्ध कृषि विरासत से जुड़ें।",
    uploadHint: "आपकी तस्वीर। एआई का सुझाव। एक शुरुआत।",
    fieldNote: "नस्ल संग्रह से",
    meetBreed: "इस नस्ल को जानें",
    photoLabel: "नस्ल की तस्वीर, पहचान का परिणाम नहीं",
    supported: "समर्थित मवेशी श्रेणियाँ",
    languages: "जानकारी के लिए भाषाएँ",
    report: "साथ रखने के लिए रिपोर्ट",
    reportFormat: "पीडीएफ",
    processEyebrow: "तस्वीर से जानकारी तक",
    processTitle: "बेहतर समझ की एक आसान शुरुआत।",
    steps: [
      { title: "स्पष्ट तस्वीर चुनें", body: "अच्छी रोशनी में एक जानवर की तस्वीर लें, जिसमें शरीर, सिर और सींग दिखाई दें।" },
      { title: "एआई का सुझाव पाएँ", body: "मॉडल एक समर्थित नस्ल और विश्वास स्कोर सुझाता है। इसे मार्गदर्शन मानें, प्रमाणित पहचान नहीं।" },
      { title: "जानें। सहेजें। खोजें।", body: "नस्ल की विशेषताएँ पढ़ें, पीडीएफ रिपोर्ट डाउनलोड करें या नस्ल संग्रह में और जानकारी पाएँ।" },
    ],
    collectionEyebrow: "अनेक नस्लें। अनेक कहानियाँ।",
    collectionTitle: "भारत की कुछ विशिष्ट नस्लों से मिलें।",
    collectionIntro: "अलग-अलग क्षेत्रों ने पशुपालन की अलग परंपराओं को आकार दिया है। परिचित चेहरों के पीछे की विविधता को जानें।",
    allBreeds: "सभी 50 नस्लें देखें",
    breedNames: { Gir: "गिर", Kankrej: "कांकरेज", Thutho: "थूथो" },
    breedRegions: { Gir: "गुजरात", Kankrej: "गुजरात और राजस्थान", Thutho: "नागालैंड" },
    breedNotes: {
      Gir: "उभरा हुआ माथा और लंबे, लटकते कान इस दुधारू नस्ल की पहचान हैं।",
      Kankrej: "दूध और कृषि कार्य, दोनों के लिए उपयोगी यह नस्ल अपने विशिष्ट घुमावदार सींगों के लिए जानी जाती है।",
      Thutho: "नागालैंड के मवेशी, जो इस क्षेत्र के पहाड़ी वातावरण के अनुकूल हैं।",
    },
    viewProfile: "नस्ल का विवरण",
    diversity: "विविधता क्यों महत्वपूर्ण है",
    diversityBody: "स्थानीय नस्लों को जानना पशुधन विविधता, ग्रामीण आजीविका और उनसे जुड़े पर्यावरण को महत्व देने की दिशा में एक कदम है।",
    diversityLink: "एफएओ से और जानें",
    guideEyebrow: "बेहतर तस्वीर। बेहतर शुरुआत।",
    guideTitle: "ज़रूरी विशेषताएँ साफ़ दिखने दें।",
    tips: [
      { title: "एक जानवर, बगल से", body: "सिर और सींगों सहित पूरा शरीर तस्वीर में रखें।" },
      { title: "प्राकृतिक, समान रोशनी", body: "गहरी छाया, धुंधली तस्वीर, फ़िल्टर और बहुत दूर से ली गई तस्वीर से बचें।" },
      { title: "निजी जानकारी दूर रखें", body: "ऐसी तस्वीर चुनें जिसमें लोग, दस्तावेज़ या व्यक्तिगत पहचान की जानकारी न हो।" },
    ],
    faqEyebrow: "शुरू करने से पहले",
    faqTitle: "कुछ ज़रूरी बातें।",
    faqs: [
      { question: "विश्वास स्कोर का क्या अर्थ है?", answer: "यह उस तस्वीर के लिए मॉडल के सुझाव में विश्वास दर्शाता है, नस्ल की पहचान की गारंटी नहीं। मिलती-जुलती नस्लें, मिश्रित वंश या अस्पष्ट तस्वीर से गलती हो सकती है। तस्वीर से आनुवंशिक पुष्टि या स्वास्थ्य निदान नहीं हो सकता।" },
      { question: "क्या दूध उत्पादन जैसे आँकड़े मेरी तस्वीर से मापे जाते हैं?", answer: "नहीं। दूध उत्पादन, वसा प्रतिशत, जलवायु सहनशीलता और बाजार मूल्य नस्ल की सामान्य संदर्भ जानकारी हैं, उस विशेष जानवर के माप नहीं। वास्तविक आँकड़े देखभाल, उम्र, स्थान और अन्य कारकों पर निर्भर करते हैं।" },
      { question: "क्या मेरी पहचान का इतिहास निजी है?", answer: "नहीं। इस संस्करण में पहचान का इतिहास साझा और सार्वजनिक है; व्यक्तिगत खाते नहीं हैं। तस्वीरें विश्लेषण के लिए सर्वर पर भेजी जाती हैं। इतिहास में पहचान का विवरण और समय दर्ज होता है। संवेदनशील या व्यक्तिगत पहचान वाली सामग्री अपलोड न करें।" },
      { question: "पहले परिणाम में अधिक समय क्यों लग सकता है?", answer: "निःशुल्क एपीआई निष्क्रिय होने पर बंद अवस्था में जा सकता है और फिर सक्रिय होने में समय ले सकता है। विश्लेषण के दौरान पृष्ठ खुला रखें। त्रुटि दिखे तो थोड़ा रुककर फिर कोशिश करें। बिना अपलोड किए भी नस्ल संग्रह देख सकते हैं।" },
    ],
    closingEyebrow: "जिज्ञासा पहला कदम है",
    closingTitle: "हर नस्ल की एक कहानी है।\nजानना शुरू करें।",
    footer: "खोजें। समझें। संरक्षित करें।",
    footerNote: "एआई से सीखें, इसे नस्ल का प्रमाण न मानें।",
  },
  gu: {
    language: "ભાષા",
    navigation: "મુખ્ય નેવિગેશન",
    skip: "મુખ્ય સામગ્રી પર જાઓ",
    carouselRole: "ફોટાની શ્રેણી",
    carouselLabel: "પશુઓની ઓલાદોના ફોટા",
    previousPhoto: "અગાઉની ઓલાદનો ફોટો",
    nextPhoto: "આગળની ઓલાદનો ફોટો",
    pauseSlideshow: "ફોટાની શ્રેણી રોકો",
    playSlideshow: "ફોટાની શ્રેણી ચાલુ કરો",
    reducedSlideshow: "ઓછી ગતિ: ફોટા જોવા તીરનો ઉપયોગ કરો",
    slideshowTiming: "દર 2 સેકન્ડે એક નવી ઓલાદ",
    photoAlt: "{breed} ઓલાદના પશુઓ",
    photoError: "આ ફોટો લોડ થયો નથી. બીજી ઓલાદ પસંદ કરવા તીરનો ઉપયોગ કરો.",
    identify: "ઓલાદ ઓળખો",
    explore: "ઓલાદો જુઓ",
    eyebrow: "વારસા સાથે જોડાણ. AIનું માર્ગદર્શન.",
    title: "તમારા પશુઓને જાણો.",
    titleAccent: "તેમની વાર્તા શોધો.",
    intro: "એક ફોટાથી વધુ ઊંડી સમજની શરૂઆત થઈ શકે છે. પશુઓની ઓલાદો અને તેમની વિશેષતાઓ જાણો, અને ભારતના સમૃદ્ધ કૃષિ વારસા સાથે જોડાઓ.",
    uploadHint: "તમારો ફોટો. AIનું સૂચન. એક શરૂઆત.",
    fieldNote: "ઓલાદ સંગ્રહમાંથી",
    meetBreed: "આ ઓલાદને જાણો",
    photoLabel: "ઓલાદનો ફોટો, ઓળખનું પરિણામ નહીં",
    supported: "સમર્થિત પશુ શ્રેણીઓ",
    languages: "જાણકારી માટે ભાષાઓ",
    report: "સાથે રાખવા માટે રિપોર્ટ",
    reportFormat: "પીડીએફ",
    processEyebrow: "ફોટાથી જાણકારી સુધી",
    processTitle: "વધુ સારી સમજની સરળ શરૂઆત.",
    steps: [
      { title: "સ્પષ્ટ ફોટો પસંદ કરો", body: "સારા પ્રકાશમાં એક પશુનો ફોટો લો, જેમાં શરીર, માથું અને શિંગડાં દેખાય." },
      { title: "AIનું સૂચન મેળવો", body: "મોડેલ એક સમર્થિત ઓલાદ અને વિશ્વાસનો સ્કોર સૂચવે છે. તેને માર્ગદર્શન માનો, પ્રમાણિત ઓળખ નહીં." },
      { title: "જાણો. સાચવો. શોધો.", body: "ઓલાદની વિશેષતાઓ વાંચો, પીડીએફ રિપોર્ટ ડાઉનલોડ કરો અથવા ઓલાદ સંગ્રહમાં વધુ જાણો." },
    ],
    collectionEyebrow: "ઘણી ઓલાદો. ઘણી વાર્તાઓ.",
    collectionTitle: "ભારતની કેટલીક વિશિષ્ટ ઓલાદોને મળો.",
    collectionIntro: "જુદા પ્રદેશોએ પશુપાલનની જુદી પરંપરાઓ ઘડી છે. પરિચિત ચહેરા પાછળની વિવિધતાને જાણો.",
    allBreeds: "બધી 50 ઓલાદો જુઓ",
    breedNames: { Gir: "ગીર", Kankrej: "કાંકરેજ", Thutho: "થૂથો" },
    breedRegions: { Gir: "ગુજરાત", Kankrej: "ગુજરાત અને રાજસ્થાન", Thutho: "નાગાલેન્ડ" },
    breedNotes: {
      Gir: "ઊપસેલું કપાળ અને લાંબા, લટકતા કાન આ દૂધાળ ઓલાદની ઓળખ છે.",
      Kankrej: "દૂધ અને ખેતીકામ બંને માટે ઉપયોગી આ ઓલાદ તેના વિશિષ્ટ વળાંકવાળાં શિંગડાં માટે જાણીતી છે.",
      Thutho: "નાગાલેન્ડના પશુઓ, જે આ વિસ્તારના પહાડી વાતાવરણને અનુકૂળ છે.",
    },
    viewProfile: "ઓલાદની વિગતો",
    diversity: "વિવિધતા કેમ મહત્વની છે",
    diversityBody: "સ્થાનિક ઓલાદોને જાણવી એ પશુધનની વિવિધતા, ગ્રામીણ આજીવિકા અને તેમની સાથે જોડાયેલા પર્યાવરણને મહત્વ આપવાની દિશામાં એક પગલું છે.",
    diversityLink: "FAO પાસેથી વધુ જાણો",
    guideEyebrow: "સારો ફોટો. સારી શરૂઆત.",
    guideTitle: "જરૂરી વિશેષતાઓ સ્પષ્ટ દેખાવા દો.",
    tips: [
      { title: "એક પશુ, બાજુથી", body: "માથું અને શિંગડાં સહિત આખું શરીર ફોટામાં રાખો." },
      { title: "કુદરતી, સમાન પ્રકાશ", body: "ઘેરા પડછાયા, ધૂંધળા ફોટા, ફિલ્ટર અને દૂરથી લીધેલા ફોટા ટાળો." },
      { title: "અંગત વિગતો દૂર રાખો", body: "લોકો, દસ્તાવેજો કે વ્યક્તિગત ઓળખની માહિતી ન હોય એવો ફોટો પસંદ કરો." },
    ],
    faqEyebrow: "શરૂ કરતાં પહેલાં",
    faqTitle: "જાણવા જેવી કેટલીક વાતો.",
    faqs: [
      { question: "વિશ્વાસના સ્કોરનો અર્થ શું છે?", answer: "તે આ ફોટા માટેના સૂચનમાં મોડેલનો વિશ્વાસ દર્શાવે છે, ઓલાદની ઓળખની ખાતરી નહીં. સરખી દેખાતી ઓલાદો, મિશ્ર વંશ કે અસ્પષ્ટ ફોટાથી ભૂલ થઈ શકે છે. ફોટાથી જિનેટિક પુષ્ટિ કે આરોગ્યનું નિદાન થઈ શકતું નથી." },
      { question: "શું દૂધ ઉત્પાદન જેવા આંકડા મારા ફોટાથી મપાય છે?", answer: "ના. દૂધ ઉત્પાદન, ચરબીની ટકાવારી, હવામાન સહનશીલતા અને બજાર કિંમત ઓલાદની સામાન્ય સંદર્ભ માહિતી છે, તે ખાસ પશુના માપ નથી. વાસ્તવિક આંકડા સંભાળ, ઉંમર, સ્થળ અને અન્ય પરિબળો પર આધાર રાખે છે." },
      { question: "શું મારી ઓળખનો ઇતિહાસ ખાનગી છે?", answer: "ના. આ આવૃત્તિમાં ઓળખનો ઇતિહાસ સહિયારો અને જાહેર છે; વ્યક્તિગત ખાતાં નથી. ફોટા વિશ્લેષણ માટે સર્વર પર મોકલાય છે. ઇતિહાસમાં ઓળખની વિગતો અને સમય નોંધાય છે. સંવેદનશીલ કે વ્યક્તિગત ઓળખ આપતી સામગ્રી અપલોડ ન કરો." },
      { question: "પહેલા પરિણામમાં વધુ સમય કેમ લાગી શકે?", answer: "મફત API ઉપયોગ ન થતો હોય ત્યારે નિષ્ક્રિય થઈ શકે છે અને ફરી સક્રિય થવામાં સમય લાગી શકે છે. વિશ્લેષણ દરમિયાન પાનું ખુલ્લું રાખો. ભૂલ દેખાય તો થોડી વાર પછી ફરી પ્રયત્ન કરો. અપલોડ કર્યા વગર પણ ઓલાદ સંગ્રહ જોઈ શકો છો." },
    ],
    closingEyebrow: "જિજ્ઞાસા એ પહેલું પગલું છે",
    closingTitle: "દરેક ઓલાદની એક વાર્તા છે.\nજાણવાની શરૂઆત કરો.",
    footer: "શોધો. સમજો. સાચવો.",
    footerNote: "AIથી શીખો, તેને ઓલાદનું પ્રમાણ ન માનો.",
  },
};
